### PR TITLE
Chrome extension

### PR DESCRIPTION
**Pull request by deepdesigns6**
Want to include extensions or should I create a separate repo?

### CODE REVIEW

**Comment by travis-g** [comment]
Did you merge your two commits from #37?

**Comment by deepdesigns6** [comment]
For some reason my work and personal github accounts got crossed, so I just deleted the branch, sorted out my config, and resubmitted. 

We'll need to add a key to the extension if you want to package it for the web store. Otherwise, you can just host the extension file.. just make sure you keep the key.

Anyway, the static files need to be integrated into the source and added to grunt, but this should do for now. I would love to take care of imgur links very soon.

**Comment by deepdesigns6** [comment]
Also yes the logo is mine.. I was going to use the mascot but I wasn't sure about licensing so I just put this together real quick. I'm not married to it or anything.

**Comment by travis-g** [comment]
Imgur links?

For now, the logo you made is excellent! I'll be merging this in ASAP, most likely once Voat stabilizes and I can test the uncommited changes I've made over the last week.

**Comment by deepdesigns6** [comment]
Some of the imgur links that aren't formatted correctly don't have the
inline show button.. I think this is a problem with RES too now actually..
hard to test since voat is down again :(

**Comment by travis-g** [comment]
Voat being down is putting a damper on a number of things. I hope it come back up soon..

If you nail down the imgur issue by all means open an issue, but I haven't seen it yet.

**Comment by deepdesigns6** [comment]
I'm just going to close this until we're a bit cleaner

**Pull request closed without merging**
